program: training_scripts/cross_validation/train-cross-validation.py
method: random
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "train"
  - "-f"
  - "allennlp_configs/adu_sciarg_scibert_split_hpt.jsonnet"
  - "--include-package"
  - "sam"
  - "-s"
  - "experiments/adu/hpt_trials/hpt_lr_only"
  - "--num_folds"
  - "2"
  - ${args}

metric:
  name: best_validation_f1-measure-overall_mean
  goal: maximize
parameters:
  trainer.optimizer.lr:
    distribution: uniform
    min: 0.00042503398047976764
    max: 0.003537718085183636
